### ISSUE TITLE
Version 3.0 Hardware

### ISSUE THREAD

**Issue by Indemnity83** [forkineye/ESPixelStick#196]
Any chance you’re going to open source the v3.0 hardware?

I’m assuming from comments and the changes of that it’s based on an ESP-12 module or similar with an SD card?

**Comment by forkineye** [comment]
Sorry, I won't be releasing any of the hardware files.  Reason being is that the last time I did, 3rd parties were producing and selling very sub-par versions of them.  Mostly hand assembled and prone to failure. Naturally, the buyers came to me when their boards didn't work.  Turns out they had purchased some very badly hand soldered versions from that were produced from my gerber files.

As for v3.0, it;'s Wemos D1 mini based with a micro SD slot and built in differential outputs for DMX support.  SD support will be coming in 4.0 (under development as the unify branch).
