### ISSUE TITLE
Im lost about pinout what pin to use...

### ISSUE THREAD

**Issue by processor83** [forkineye/ESPixelStick#302]
I need some help about esp32 pinout.

i looked everywhere in the code but found nothing but now i suspect its because it is uart1 and uart2 tx pin and it connat be changed so its not defined anywhere ?

is it GPIO17 and GPIO09??

so io17 and sd2 on those wemos d32 mini ?

and on esp8266 it is GPIO02(D4)

Thank you for you help.

**Comment by MartinMueller2003** [comment]
Since this information is shared by multiple output types, it is found in common.hpp. However in the esp32 these are "well known" names so they are not defined explicitly. 
typedef enum
{    GPIO_NUM_2  = 2,    GPIO_NUM_10 = 10,    GPIO_NUM_13 = 13,
} gpio_num_t;
typedef enum{    UART_NUM_0 = 0,    UART_NUM_1,    UART_NUM_2} uart_port_t;
Then in OutputCommon.cpp you get a table that tells the code how to map the IO for each of the three possible output paths:
static const OutputChannelIdToGpioAndPortEntry_t OutputChannelIdToGpioAndPort[] ={    {gpio_num_t::GPIO_NUM_2,  uart_port_t::UART_NUM_1},#ifdef ARDUINO_ARCH_ESP32    {gpio_num_t::GPIO_NUM_13, uart_port_t::UART_NUM_2},#endif // def ARDUINO_ARCH_ESP32    {gpio_num_t::GPIO_NUM_10, uart_port_t (-1)},};
The code uses these values. It is trivial to make them configurable and you can easily change the in this table.
Martin    On Tuesday, February 16, 2021, 02:16:22 PM EST, processor83 <notifications@github.com> wrote:  
 
 


I need some help about esp32 pinout.

i looked everywhere in the code but found nothing but now i suspect its because it is uart1 and uart2 tx pin and it connat be changed so its not defined anywhere ?

is it GPIO17 and GPIO09??

so io17 and sd2 on those wemos d32 mini ?

and on esp8266 it is GPIO02(D4)

Thank you for you help.

**Comment by processor83** [comment]
I don't know why I cannot understand this..   on esp32 it use gpio02 and gpio10 or 10 and 13?

**Comment by MartinMueller2003** [comment]
This is the current mapping and it CAN be changed:

gpio_num_t::GPIO_NUM_2,   uart_port_t::UART_NUM_1
gpio_num_t::GPIO_NUM_13, uart_port_t::UART_NUM_2

With that said, I cannot predict how the module manufacturer connects the GPIOs to module pins. That is different for each module.

**Comment by processor83** [comment]
I'm actually designing my module with sd card and optional network. I will wait officiel design or maintain a fork with my pinout. I'm not super good at programming that why I'm lost! So thi tell which user is used on a gpio?

Thank you for taking time to help me with this.  I will have my esp32 and lan8720 modules soon and will be able to test the firmware and the Ethernet fork.

**Comment by MartinMueller2003** [comment]
Would you like a call on skype or slack?
Martin
    On Thursday, February 25, 2021, 07:47:43 AM EST, processor83 <notifications@github.com> wrote:  
 
 


I'm actually designing my module with sd card and optional network. I will wait officiel design or maintain a fork with my pinout. I'm not super good at programming that why I'm lost! So thi tell which user is used on a gpio?

Thank you for taking time to help me with this. I will have my esp32 and lan8720 modules soon and will be able to test the firmware and the Ethernet fork.

**Comment by processor83** [comment]
That would be nice but my English is not so good I will understand you but I'm not sure you will understand me haha! Let me know how to contact you and I will be more then happy to talk with you!

**Comment by MartinMueller2003** [comment]
skype martin.mueller.brainware
i am pretty good at understanding broken english.
martin

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 25, 2021 at 16:17, processor83<notifications@github.com> wrote:   


That would be nice but my English is not so good I will understand you but I'm not sure you will understand me haha! Let me know how to contact you and I will be more then happy to talk with you!
