### ISSUE TITLE
unable to assign GPIO0/D3 as a valid relay output pin

### ISSUE THREAD

**Issue by garymueller** [forkineye/ESPixelStick#375]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
head

**Hardware Version**
wemos mini D1

**Binary release or compiled yourself?**
compiled

**Operating System (and version)**
windows 10

**Web Browser (and version)**
google chrome Version 94.0.4606.61 (Official Build) (64-bit)

**Access Point**
??

**Describe the bug**
Unable to assign GPIO0 as a valid option for relay output. This is due to the Relay_DEFAULT_GPIO_ID being assigned to 0 which is also the value of GPIO0.  The validate function compares the gpioID to the Relay_DEFAULT_GPIO_ID and if they are the same disables the relay.  Solution is to use a value for default pin that does not overlap with actual pin values.  I tried -1 and it worked ... but the front end didnt appear to like it.

**Comment by MartinMueller2003** [comment]
@Gary. Any relationship to Arnold and Meta Mueller?
Martin
    On Saturday, October 2, 2021, 02:46:46 PM EDT, Gary Mueller ***@***.***> wrote:  
 
 


--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

ESPixelStick Firmware Version
head

Hardware Version
wemos mini D1

Binary release or compiled yourself?
compiled

Operating System (and version)
windows 10

Web Browser (and version)
google chrome Version 94.0.4606.61 (Official Build) (64-bit)

Access Point
??

Describe the bug
Unable to assign GPIO0 as a valid option for relay output. This is due to the Relay_DEFAULT_GPIO_ID being assigned to 0 which is also the value of GPIO0. The validate function compares the gpioID to the Relay_DEFAULT_GPIO_ID and if they are the same disables the relay. Solution is to use a value for default pin that does not overlap with actual pin values. I tried -1 and it worked ... but the front end didnt appear to like it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by garymueller** [comment]
no relation that I'm aware of. Mueller ancestry runs through Illinois/Michigan areas.

**Comment by Panzercou** [comment]
Will the wemos d1 mini have more capacity than 1200 leds?
Can't you put 10,000 leds?

**Comment by Panzercou** [comment]
How can I change the pin, or the number of leds?
