### ISSUE TITLE
Minor error on SD card file detail

### ISSUE THREAD

**Issue by brmeadows2841** [forkineye/ESPixelStick#461]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
version 4 beta 4

**Hardware Version**
ESP32

**Binary release or compiled yourself?**

compiled
**Operating System (and version)**
Win 11

**Web Browser (and version)**

Chrome
**Access Point**

**Describe the bug**
When SEQ files are uploaded to the SD card file details are incorrectly displayed.
Example:
Notice the T at end of date and Z at end of time.

Wizards in Winter -test 4.fseq | 2022-01-15T08:28:08.000Z

**Comment by MartinMueller2003** [comment]
That is a specific time format that conforms to the ISO time display specification. The value between the T and the Z tell you the string includes a time and that the Time Zone offset that was applied is zero.

**Comment by brmeadows2841** [comment]
I understand.

**Comment by MartinMueller2003** [comment]
In reality the time info is almost useless since the ESP has no access to a time server (no NTP and no RTC) so the time is "taken" from the browser at the moment you transfer the files. That is at best a close approximation and at worst misleading. I suspect we may want to remove the time portion of the string.

**Comment by brmeadows2841** [comment]
It would be beneficial to have a time stamp on the seq upload.

**Comment by MartinMueller2003** [comment]
I updated the time stamps to a more common format.
