### ISSUE TITLE
seaprate view stream out from the testing effects ?

### ISSUE THREAD

**Issue by penfold42** [forkineye/ESPixelStick#53]
Maybe a checkbox to enable it and leave the dropdown to focus on running effects ?

What do you think ?

**Comment by forkineye** [comment]
I have two thoughts on this.. 1) Just leave it at the bottom of the list as different test modes are added to lessen UI clutter..  2) Separate out stand-alone effects and diagnostic stuff.  I do plan on adding an internal test pattern / effect list that can be published via MQTT so that there are other options besides just static when using MQTT with home automation stuff.  Just not sure how I want to do it yet, but it will be synced with the effects from the test drop-down.

**Comment by penfold42** [comment]
Thinking about this again - my vote would be to separate it to a discrete section on the navbar.

If the effects become more sophisticated, configurable or support sdcard playback this becomes even more useful

**Comment by Kamal-Sonani** [comment]
@penfold42 thats what i want to do 😎

**Comment by penfold42** [comment]
im looking at it now

**Comment by penfold42** [comment]
done, #92
