### ISSUE TITLE
V4 xLights input/outputs

### ISSUE THREAD

**Issue by cybercop23** [forkineye/ESPixelStick#651]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
FW Version4.x-dev
Build DateAug 16 2023 - 20:47:42
ArchitectureESP32

**Hardware Version**
Board Nameesp32_quinled_uno_ae_plus

**Binary release or compiled yourself?**
Released

**Operating System (and version)**
Win 11

**Web Browser (and version)**
Chrome

**Access Point**
No

**Describe the bug**
With the latest changes in V4 and the mods in xLights, Uploads Inputs "works" not much to be done there, but Upload Outputs gets a core dump and reboots. If I manually configure Outputs, they get wiped and disabled by the same Upload Outputs/reboot.

FPP Connect to the latest v4 and without checking the hat box, works and sends the sequence without issues.

**Comment by MartinMueller2003** [comment]
There are two bug here. 

1. First is a missing config key term that causes the ESP to discard the new config when it is sent by xLights.  Fixed in xLights PR#3932
2. A race condition in the output config processing. Fixed in V4 PR#652
New ESP Dist at
https://drive.google.com/drive/folders/1bGrkXSMoGjWtX5iWspPFRogM2G6c1VXu?usp=sharing
